global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'big-market-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - '172.24.58.32:8091'
          - '172.24.58.32:8092'
        labels:
          app: 'big-market-app'